name = "vless"
main = "_worker.js"
compatibility_date = "2026-08-28"

# Cloudflare Workers compatibility flags
# Enable Node.js compatibility for crypto.subtle
compatibility_flags = ["nodejs_compat"]

# ============================================
# ENVIRONMENT VARIABLES (Public)
# ============================================
[vars]



PROXYIP = "cdn-b100.xn--b6gac.eu.org"  # wrangler secret put PROXYIP
PROXY_LIST_URL = "https://raw.githubusercontent.com/gprox-galaxy/Cloudflare-Galaxytunnel/refs/heads/main/PROXYIP.txt"              # wrangler secret put PROXY_LIST_URL
DNS_RESOLVER_URL = ""            # wrangler secret put DNS_RESOLVER_URL

