name = "supermeno"
main = "_worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]

keep_vars = true

[vars]
UUID = ""
# If TROJAN_PASS is empty, it automatically uses the UUID value for Trojan authentication
TROJAN_PASS = ""
PASSWORD = "galaxy-tunnel"
MASK_PAGE = "true"
WS_PATH = "galaxy-tunnel"
PROXYIP = "cdn-b100.xn--b6gac.eu.org"
PROXY_LIST_URL = "https://raw.githubusercontent.com/gprox-galaxy/Cloudflare-Galaxytunnel/refs/heads/main/PROXYIP.txt"
DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
